/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "user.pb-c.h"
void   user__init
                     (User         *message)
{
  static User init_value = USER__INIT;
  *message = init_value;
}
size_t user__get_packed_size
                     (const User *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__pack
                     (const User *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__pack_to_buffer
                     (const User *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User *
       user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User *)
     protobuf_c_message_unpack (&user__descriptor,
                                allocator, len, data);
}
void   user__free_unpacked
                     (User *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   users__init
                     (Users         *message)
{
  static Users init_value = USERS__INIT;
  *message = init_value;
}
size_t users__get_packed_size
                     (const Users *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &users__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t users__pack
                     (const Users *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &users__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t users__pack_to_buffer
                     (const Users *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &users__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Users *
       users__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Users *)
     protobuf_c_message_unpack (&users__descriptor,
                                allocator, len, data);
}
void   users__free_unpacked
                     (Users *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &users__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
char user__username__default_value[] = "jack.zh";
static const ProtobufCFieldDescriptor user__field_descriptors[4] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(User, username),
    NULL,
    &user__username__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(User, password),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(User, has_age),
    PROTOBUF_C_OFFSETOF(User, age),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(User, email),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__field_indices_by_name[] = {
  2,   /* field[2] = age */
  3,   /* field[3] = email */
  1,   /* field[1] = password */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor user__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "User",
  "User",
  "User",
  "",
  sizeof(User),
  4,
  user__field_descriptors,
  user__field_indices_by_name,
  1,  user__number_ranges,
  (ProtobufCMessageInit) user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor users__field_descriptors[1] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Users, n_user),
    PROTOBUF_C_OFFSETOF(Users, user),
    &user__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned users__field_indices_by_name[] = {
  0,   /* field[0] = user */
};
static const ProtobufCIntRange users__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor users__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Users",
  "Users",
  "Users",
  "",
  sizeof(Users),
  1,
  users__field_descriptors,
  users__field_indices_by_name,
  1,  users__number_ranges,
  (ProtobufCMessageInit) users__init,
  NULL,NULL,NULL    /* reserved[123] */
};
